SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO
WHERE ITEM_INFO.ITEM_ID NOT IN (
SELECT DISTINCT ITEM_TREE.PARENT_ITEM_ID
FROM ITEM_TREE
WHERE ITEM_TREE.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_INFO.ITEM_ID DESC